name: cities

networks:
  app-network:
    driver: bridge

services:
  # Сервис для PostgreSQL
  postgresDB:
    image: postgres
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: pgSuperSecretMnogaBycaBab
      POSTGRES_DB: population
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes: 
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresUser"]
      timeout: 5s
      retries: 20

  # Сервис для Express.js
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgresDB:
        condition: service_healthy
    environment:
      DB_HOST: postgresDB
      DB_PORT: 5432
      DB_USER: postgresUser
      DB_PASSWORD: pgSuperSecretMnogaBycaBab
      DB_NAME: population
    ports:
      - "3000:3000"  # Пробрасываем порт 3000
    networks:
      - app-network
    command: ["./run_scripts.sh"]

volumes:
  postgres:
    driver: local